version: 0.0.{build}

branches:
  only:
  - master

clone_depth: 20

before_build:
- cmd: nuget restore

build:
  project: Extensions.sln
  verbosity: minimal
 
after_build:
- cmd: nuget pack Extensions\Extensions.csproj -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
- path: '*.nupkg'
  name: nuget-package
  
deploy:
- provider: NuGet
  server: https://www.myget.org/F/eliekstein/api/v2/package

  api_key:
    secure: rcuLPZxD9M8/DE6fCI4FcYmvExEXPbvdnnhTrQNeTmF6FyfofibZg8MDU+8mRS9R
  artifact: nuget-package
  on:
    branch: master
